## Structure: outermost layer is survey (e.g., DES, LSST, ROMAN, etc.) Inner layer indicates data file type (e.g., DUMP, SIM, DATA).
# The subscript indicates the SN type (e.g., IA, CC, etc.) ALL indicates a mixture of SN types.

FIT_OPTIONS:
  RATE_FUNCTION: power_law

DES:
  FIT_OPTIONS:
    RATE_FUNC: power_law
    RATE_PARAMS: 2.27E-5, 1.7
    Z_BINS: 9
    MIN_Z: 0.2
    MAX_Z: 0.9
  CUTS:
    x1: -3, 3
    c: -0.3, 0.3
  DUMP_IA:
    PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/1_SIM/DESIA_NOMINAL/PIP_D5YR_RATEPZ_BCOR_NOMINAL_DESIA_NOMINAL/PIP_D5YR_RATEPZ_BCOR_NOMINAL_DESIA_NOMINAL.DUMP.gz
  SIM_IA:
    PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_D5_DESIA_NOMINAL/output/PIP_D5YR_RATEPZ_BCOR_NOMINAL_DESIA_NOMINAL/FITOPT001.FITRES.gz
    ZCOL: zHD
    # Rick said to always use zHD
  # DATA_IA:
  #   PATH: #/scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_D5_DESIA_NOMINAL/output/PIP_D5YR_RATEPZ_BCOR_NOMINAL_DESIA_NOMINAL/FITOPT001.FITRES.gz
  #     - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_Dsys_DATADES_SIM/output/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_IA-0001/FITOPT001.FITRES.gz
  #     - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_Dsys_DATADES_SIM/output/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_IA-0002/FITOPT001.FITRES.gz
  #     - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_Dsys_DATADES_SIM/output/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_IA-0003/FITOPT001.FITRES.gz
  #     - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_Dsys_DATADES_SIM/output/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_IA-0004/FITOPT001.FITRES.gz
  #     - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_Dsys_DATADES_SIM/output/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_IA-0005/FITOPT001.FITRES.gz
  #   ZCOL: zHD
  # DATA_CC:
  #   PATH:
  #     - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_Dsys_DATADES_SIM_CC/output/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_CC-0001/FITOPT001.FITRES.gz
  #     - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_Dsys_DATADES_SIM_CC/output/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_CC-0002/FITOPT001.FITRES.gz
  #     - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_Dsys_DATADES_SIM_CC/output/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_CC-0003/FITOPT001.FITRES.gz
  #     - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_Dsys_DATADES_SIM_CC/output/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_CC-0004/FITOPT001.FITRES.gz
  #     - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_Dsys_DATADES_SIM_CC/output/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_CC-0005/FITOPT001.FITRES.gz
  #   ZCOL: zHD

  DATA_ALL:
    PATH:
      - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_Dsys_DATADESSMP/output/DES-SN5YR_DES/FITOPT001.FITRES.gz
    ZCOL: zHD
  #  Rick said to always use zHD


  DUMP_CC:
    PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/1_SIM/DATADES_SIM_CC/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_CC-0001/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_CC-0001.DUMP.gz
  # change the below to a different sim file
  SIM_CC:
    PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_Dsys_DATADES_SIM_CC/output/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_CC-0002/FITOPT000.FITRES.gz
    #ZCOL: zPHOT
    ZCOL: zHD
    # Rick said to always use zHD
