## Structure: outermost layer is survey (e.g., DES, LSST, ROMAN, etc.) Inner layer indicates data file type (e.g., DUMP, SIM, DATA).
# The subscript indicates the SN type (e.g., IA, CC, etc.) ALL indicates a mixture of SN types.

FIT_OPTIONS:
  RATE_FUNCTION: double_power_law
SDSS:
  FIT_OPTIONS:
    RATE_FUNC: power_law
    RATE_PARAMS: 2.27E-5, 1.7
    Z_BINS: 9
    MIN_Z: 0.05
    MAX_Z: 0.4
    CC_ARE_SEPARATE: false

  CUTS:
    x1: -3, 3
    c: -0.3, 0.3
    FITPROB: 0.001, 1000
    PKMJDERR: 0, 2
  DUMP_ALL:
    PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFM-SDSS-RATE/1_SIM/SDSS_BCOR/PIP_CFM-SDSS-RATE_SDSS_BCOR/PIP_CFM-SDSS-RATE_SDSS_BCOR.DUMP.gz 
    ZCOL: GENZ
    SNTYPECOL: GENTYPE
    IA_VALS:
      - 1
    # Rick said to always use zHD
  SIM_ALL:
    PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFM-SDSS-RATE/5_MERGE/MERGE_SDSSFIT_SDSS_BCOR/output/PIP_CFM-SDSS-RATE_SDSS_BCOR/FITOPT000.FITRES.gz
    ZCOL: zPHOT
    SNTYPECOL: SIM_GENTYPE
    IA_VALS:
      - 1
  DATA_ALL:
    PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFM-SDSS-RATE/5_MERGE/MERGE_SDSSFIT_DATASDSS/output/SDSS_allCandidates+BOSS_P19/FITOPT000.FITRES.gz
    ZCOL: zPHOT


DES:
  FIT_OPTIONS:
    RATE_FUNC: power_law
    RATE_PARAMS: 2.27E-5, 1.7
    Z_BINS: 10
    MIN_Z: 0.1
    MAX_Z: 0.9

  CUTS:
    x1: -3, 3
    c: -0.3, 0.3
    FITPROB: 0.01, 10000
    PKMJDERR: 0, 2
  DUMP_IA:
    PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/1_SIM/DESIA_NOMINAL/PIP_D5YR_RATEPZ_BCOR_NOMINAL_DESIA_NOMINAL/PIP_D5YR_RATEPZ_BCOR_NOMINAL_DESIA_NOMINAL.DUMP.gz
  SIM_IA:
    PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_D5_DESIA_NOMINAL/output/PIP_D5YR_RATEPZ_BCOR_NOMINAL_DESIA_NOMINAL/FITOPT001.FITRES.gz
    ZCOL: zHD
    # Rick said to always use zHD


  DATA_ALL:
    PATH:
      - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_Dsys_DATADESSMP/output/DES-SN5YR_DES/FITOPT001.FITRES.gz
    ZCOL: zHD
  #  Rick said to always use zHD


  DUMP_CC:
    PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/1_SIM/DATADES_SIM_CC/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_CC-0001/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_CC-0001.DUMP.gz
  # change the below to a different sim file
  SIM_CC:
    PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_Dsys_DATADES_SIM_CC/output/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_CC-0002/FITOPT000.FITRES.gz
    #ZCOL: zPHOT
    ZCOL: zHD
    # Rick said to always use zHD