# Structure: outermost layer is survey (e.g., DES, LSST, ROMAN, etc.) Inner layer indicates data file type (e.g., DUMP, SIM, DATA).
# The subscript indicates the SN type (e.g., IA, CC, etc.) ALL indicates a mixture of SN types.

FIT_OPTIONS:
  RATE_FUNCTION: power_law

LOWZ:
  FIT_OPTIONS:
    RATE_FUNC: power_law
    RATE_PARAMS: 2.27E-5, 1.7
    Z_BINS: 4
    MIN_Z: 0.0025
    MAX_Z: 0.1
    CC_ARE_SEPARATE: true

  SIM_IA:
    #PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFMLOWZ_D5YR_BCOR_CUTS/1_SIM/BIASCORSIM_LOWZ/PIP_CFMLOWZ_D5YR_BCOR_CUTS_BIASCORSIM_LOWZ/*HEAD.FITS.gz
    PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFMLOWZ_D5YR_NEWCUTS_BCOR/1_SIM/BIASCORSIM_LOWZ/PIP_CFMLOWZ_D5YR_NEWCUTS_BCOR_BIASCORSIM_LOWZ/*HEAD.FITS.gz
    ZCOL: REDSHIFT_FINAL
    TRUEZCOL: SIM_REDSHIFT_CMB
  DUMP_IA:
    #PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFMLOWZ_D5YR_BCOR_CUTS/1_SIM/BIASCORSIM_LOWZ/PIP_CFMLOWZ_D5YR_BCOR_CUTS_BIASCORSIM_LOWZ/PIP_CFMLOWZ_D5YR_BCOR_CUTS_BIASCORSIM_LOWZ.DUMP.gz
    PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFMLOWZ_D5YR_NEWCUTS_BCOR/1_SIM/BIASCORSIM_LOWZ/PIP_CFMLOWZ_D5YR_NEWCUTS_BCOR_BIASCORSIM_LOWZ/PIP_CFMLOWZ_D5YR_NEWCUTS_BCOR_BIASCORSIM_LOWZ.DUMP.gz
    ZCOL: GENZ
  # DATA_IA:
  #   PATH:
  #     - /project2/rkessler/SURVEYS/DES/USERS/cmeldorf/DES-SN5YR_LOWZ_HEAD.FITS.gz
  #   ZCOL: REDSHIFT_FINAL


  # DUMP_IA:
  #   PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFMLOWZ_D5YR_BIASCOR/1_SIM/BIASCORSIM_LOWZ/PIP_CFMLOWZ_D5YR_BIASCOR_BIASCORSIM_LOWZ/PIP_CFMLOWZ_D5YR_BIASCOR_BIASCORSIM_LOWZ.DUMP.gz
  #   ZCOL: GENZ
  # SIM_IA:
  #   PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFMLOWZ_D5YR_BIASCOR/1_SIM/BIASCORSIM_LOWZ/PIP_CFMLOWZ_D5YR_BIASCOR_BIASCORSIM_LOWZ/*HEAD.FITS.gz
  #   ZCOL: REDSHIFT_FINAL
  #   TRUEZCOL: SIM_REDSHIFT_CMB
  DATA_IA:
    PATH:
      - /project2/rkessler/SURVEYS/DES/USERS/cmeldorf/DES-SN5YR_LOWZ_HEAD.FITS.gz
      - /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFMLOWZ_D5YR_SIM_NOMINAL/1_SIM/DATALOWZSIM/PIP_CFMLOWZ_D5YR_SIM_NOMINAL_DATALOWZSIM-0001/PIP_CFMLOWZ_D5YR_SIM_NOMIf2902_SNIaMODEL00-0001_HEAD.FITS.gz
      - /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFMLOWZ_D5YR_NEWCUTS_SIM_NOMINAL/1_SIM/DATALOWZSIM/PIP_CFMLOWZ_D5YR_NEWCUTS_SIM_NOMINAL_DATALOWZSIM-0001/PIP_CFMLOWZ_D5YR_NEWCUTS_1b130_SNIaMODEL00-0001_HEAD.FITS.gz

    ZCOL: REDSHIFT_FINAL
