# Structure: outermost layer is survey (e.g., DES, LSST, ROMAN, etc.) Inner layer indicates data file type (e.g., DUMP, SIM, DATA).
# The subscript indicates the SN type (e.g., IA, CC, etc.) ALL indicates a mixture of SN types.

FIT_OPTIONS:
  RATE_FUNCTION: power_law

LOWZ:
  FIT_OPTIONS:
    Z_BINS: 4
    MIN_Z: 0.0
    MAX_Z: 0.1
    CC_ARE_SEPARATE: true

  SIM_IA:
    PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFMLOWZ_D5YR_BCOR_CUTS/1_SIM/BIASCORSIM_LOWZ/PIP_CFMLOWZ_D5YR_BCOR_CUTS_BIASCORSIM_LOWZ/*HEAD.FITS.gz
    ZCOL: HOSTGAL_SPECZ
    TRUEZCOL: SIM_REDSHIFT_CMB
  DUMP_IA:
    PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFMLOWZ_D5YR_BCOR_CUTS/1_SIM/BIASCORSIM_LOWZ/PIP_CFMLOWZ_D5YR_BCOR_CUTS_BIASCORSIM_LOWZ/PIP_CFMLOWZ_D5YR_BCOR_CUTS_BIASCORSIM_LOWZ.DUMP.gz
    ZCOL: GENZ
  DATA_IA:
    PATH:
      - /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFMLOWZ_D5YR_SIM_NOMINAL/1_SIM/DATALOWZSIM/PIP_CFMLOWZ_D5YR_SIM_NOMINAL_DATALOWZSIM-0001/PIP_CFMLOWZ_D5YR_SIM_NOMIf2902_SNIaMODEL00-0001_HEAD.FITS.gz
      - /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFMLOWZ_D5YR_SIM_NOMINAL/1_SIM/DATALOWZSIM/PIP_CFMLOWZ_D5YR_SIM_NOMINAL_DATALOWZSIM-0002/PIP_CFMLOWZ_D5YR_SIM_NOMIf2902_SNIaMODEL00-0002_HEAD.FITS.gz
      - /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFMLOWZ_D5YR_SIM_NOMINAL/1_SIM/DATALOWZSIM/PIP_CFMLOWZ_D5YR_SIM_NOMINAL_DATALOWZSIM-0003/PIP_CFMLOWZ_D5YR_SIM_NOMIf2902_SNIaMODEL00-0003_HEAD.FITS.gz
      - /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFMLOWZ_D5YR_SIM_NOMINAL/1_SIM/DATALOWZSIM/PIP_CFMLOWZ_D5YR_SIM_NOMINAL_DATALOWZSIM-0004/PIP_CFMLOWZ_D5YR_SIM_NOMIf2902_SNIaMODEL00-0004_HEAD.FITS.gz
      - /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFMLOWZ_D5YR_SIM_NOMINAL/1_SIM/DATALOWZSIM/PIP_CFMLOWZ_D5YR_SIM_NOMINAL_DATALOWZSIM-0005/PIP_CFMLOWZ_D5YR_SIM_NOMIf2902_SNIaMODEL00-0005_HEAD.FITS.gz

    ZCOL: HOSTGAL_SPECZ
    #PATH:
    #  - /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFMLOWZ_D5YR_SIM_NOMINAL/1_SIM/DATALOWZSIM/PIP_CFMLOWZ_D5YR_SIM_NOMINAL_DATALOWZSIM-0001/PIP_CFMLOWZ_D5YR_SIM_NOMIf2902_SNIaMODEL00-0001_HEAD.FITS.gz


# DES:
#   FIT_OPTIONS:
#     CC_ARE_SEPARATE: true
#   DUMP_IA:
#     PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/1_SIM/DESIA_NOMINAL/PIP_D5YR_RATEPZ_BCOR_NOMINAL_DESIA_NOMINAL/PIP_D5YR_RATEPZ_BCOR_NOMINAL_DESIA_NOMINAL.DUMP.gz
#   SIM_IA:
#      PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_D5_DESIA_NOMINAL/output/PIP_D5YR_RATEPZ_BCOR_NOMINAL_DESIA_NOMINAL/FITOPT000.FITRES.gz
#      ZCOL: HOST_ZPHOT
#   DATA_IA:
#      PATH:
#       - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_Dsys_DATADES_SIM/output/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_IA-0001/FITOPT000.FITRES.gz
#      ZCOL: HOST_ZPHOT
#   DUMP_CC:
#     PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/1_SIM/DATADES_SIM_CC/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_CC-0001/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_CC-0001.DUMP.gz
#   # change the below to a different sim file
#   SIM_CC:
#     PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_Dsys_DATADES_SIM_CC/output/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_CC-0002/FITOPT000.FITRES.gz
#     ZCOL: HOST_ZPHOT
#   DATA_CC:
#     PATH:
#       - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_Dsys_DATADES_SIM_CC/output/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_CC-0001/FITOPT000.FITRES.gz
#     ZCOL: HOST_ZPHOT

