# Structure: outermost layer is survey (e.g., DES, LSST, ROMAN, etc.) Inner layer indicates data file type (e.g., DUMP, SIM, DATA).
# The subscript indicates the SN type (e.g., IA, CC, etc.) ALL indicates a mixture of SN types.

FIT_OPTIONS:
  RATE_FUNCTION: power_law


DES:
  CC_ARE_SEPARATE: true
  DUMP_IA:
    #PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/1_SIM/DESIA_NOMINAL/PIP_D5YR_RATEPZ_BCOR_NOMINAL_DESIA_NOMINAL/PIP_D5YR_RATEPZ_BCOR_NOMINAL_DESIA_NOMINAL.DUMP.gz
    PATH: /project2/rkessler/SURVEYS/ROMAN/USERS/cmeldorf/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_IA-0001/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_IA-0001.DUMP.gz
  SIM_IA:
     PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_D5_DESIA_NOMINAL/output/PIP_D5YR_RATEPZ_BCOR_NOMINAL_DESIA_NOMINAL/FITOPT000.FITRES.gz
     ZCOL: HOST_ZPHOT
  DATA_IA:
     PATH:
      - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_Dsys_DATADES_SIM/output/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_IA-0001/FITOPT000.FITRES.gz
     ZCOL: HOST_ZPHOT
  DUMP_CC:
    PATH: /project2/rkessler/SURVEYS/ROMAN/USERS/cmeldorf/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_CC-0001/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_CC-0001.DUMP.gz
  # change the below to a different sim file
  SIM_CC:
    PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_Dsys_DATADES_SIM_CC/output/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_CC-0002/FITOPT000.FITRES.gz
    ZCOL: HOST_ZPHOT
  DATA_CC:
    PATH:
      - /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATEPZ_ANALYSIS/5_MERGE/MERGE_Dsys_DATADES_SIM_CC/output/PIP_D5YR_RATEPZ_SIM_NOMINAL_DATADESSIM_CC-0001/FITOPT000.FITRES.gz
    ZCOL: HOST_ZPHOT

ROMAN:
  CC_ARE_SEPARATE: false
  DUMP_ALL:
    PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFM_ROTAC_BCOR/1_SIM/SUPERNOVA/PIP_CFM_ROTAC_BCOR_SUPERNOVA/PIP_CFM_ROTAC_BCOR_SUPERNOVA.DUMP.gz
    # ZCOL: ZCMB
    # SNTYPECOL: SNTYPE
    # IA_VALS:
    #   - 10
    #PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFM_ROTAC_PZ/1_SIM/SUPERNOVA/PIP_CFM_ROTAC_PZ_SUPERNOVA/PIP_CFM_ROTAC_PZ_SUPERNOVA.DUMP.gz
    ZCOL: ZCMB
    SNTYPECOL: SNTYPE
    IA_VALS:
      - 10
  SIM_ALL:
    # PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFM_ROTAC_BCOR/1_SIM/SUPERNOVA/PIP_CFM_ROTAC_BCOR_SUPERNOVA/PIP_CFM_ROTAC_BCOR_SUPERNOVA_SNIaMODEL00-0001_HEAD.FITS.gz
    # ZCOL: REDSHIFT_FINAL
    SNTYPECOL: SNTYPE
    IA_VALS:
      - 10
    #PATH: /home/colefmeldorf/sauron/cfm_roman_data_IA_ONLY.csv
    PATH: /home/colefmeldorf/sauron/cfm_roman_data.csv
    ZCOL: REDSHIFT_FINAL
    TRUEZCOL: SIM_REDSHIFT_CMB
  DATA_ALL:
    #PATH: /home/colefmeldorf/sauron/cfm_roman_data_IA_ONLY.csv
    PATH: /home/colefmeldorf/sauron/cfm_roman_data.csv
    ZCOL: REDSHIFT_FINAL